export const products = [
  {
    id: 1,
    name: "Tomato Hybrid Seeds",
    category: "Seeds",
    price: 450,
    unit: "100g packet",
    brand: "Nunhems",
    description: "High yield hybrid tomato seeds with disease resistance",
    image: "https://via.placeholder.com/300x200?text=Tomato+Seeds",
    rating: 4.5,
    stock: 150,
    storeId: 1
  },
  {
    id: 2,
    name: "Basmati Rice Seeds",
    category: "Seeds",
    price: 1200,
    unit: "1kg packet",
    brand: "Bayer",
    description: "Premium quality basmati rice seeds for aromatic yield",
    image: "https://via.placeholder.com/300x200?text=Rice+Seeds",
    rating: 4.7,
    stock: 80,
    storeId: 1
  },
  {
    id: 3,
    name: "NPK 19:19:19 Fertilizer",
    category: "Fertilizers",
    price: 850,
    unit: "50kg bag",
    brand: "IFFCO",
    description: "Balanced NPK fertilizer for all crops",
    image: "https://via.placeholder.com/300x200?text=NPK+Fertilizer",
    rating: 4.6,
    stock: 45,
    storeId: 1
  },
  {
    id: 4,
    name: "Vermicompost",
    category: "Fertilizers",
    price: 300,
    unit: "25kg bag",
    brand: "Organic Green",
    description: "100% organic vermicompost for healthy soil",
    image: "https://via.placeholder.com/300x200?text=Vermicompost",
    rating: 4.8,
    stock: 120,
    storeId: 3
  },
  {
    id: 5,
    name: "Neem Oil",
    category: "Pesticides",
    price: 280,
    unit: "500ml",
    brand: "Neem Foundation",
    description: "100% pure neem oil for organic farming",
    image: "https://via.placeholder.com/300x200?text=Neem+Oil",
    rating: 4.7,
    stock: 150,
    storeId: 3
  },
  {
    id: 6,
    name: "Steel Khurpi",
    category: "Tools & Equipment",
    price: 150,
    unit: "1 piece",
    brand: "Kisan Kraft",
    description: "Heavy duty steel hand tool for farming",
    image: "https://via.placeholder.com/300x200?text=Steel+Khurpi",
    rating: 4.5,
    stock: 200,
    storeId: 1
  },
  {
    id: 7,
    name: "Power Sprayer",
    category: "Tools & Equipment",
    price: 4500,
    unit: "1 piece",
    brand: "ASPEE",
    description: "16L battery operated power sprayer",
    image: "https://via.placeholder.com/300x200?text=Power+Sprayer",
    rating: 4.6,
    stock: 25,
    storeId: 2
  },
  {
    id: 8,
    name: "Drip Irrigation Kit",
    category: "Irrigation",
    price: 2500,
    unit: "1/4 acre kit",
    brand: "Jain Irrigation",
    description: "Complete drip irrigation system for small farms",
    image: "https://via.placeholder.com/300x200?text=Drip+Kit",
    rating: 4.8,
    stock: 30,
    storeId: 3
  },
  {
    id: 9,
    name: "Cattle Feed",
    category: "Animal Feed",
    price: 800,
    unit: "50kg bag",
    brand: "Godrej",
    description: "Nutritious cattle feed for milk production",
    image: "https://via.placeholder.com/300x200?text=Cattle+Feed",
    rating: 4.4,
    stock: 75,
    storeId: 2
  },
  {
    id: 10,
    name: "Safety Gloves",
    category: "Protective Gear",
    price: 120,
    unit: "1 pair",
    brand: "Safety First",
    description: "Rubber gloves for pesticide handling",
    image: "https://via.placeholder.com/300x200?text=Safety+Gloves",
    rating: 4.3,
    stock: 300,
    storeId: 1
  }
];